apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-api-chart.fullname" . }}
  labels:
    {{- include "demo-api-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "demo-api-chart.selectorLabels" . | nindent 4 }}
