name: Build and Push Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Set image tag
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
    - name: Build and Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-api:${{ env.IMAGE_TAG }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-api:${{ env.IMAGE_TAG }}
