name: Build and Test Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t demo-api-service .

    - name: Run container and test with curl
      run: |
        docker run -d -p 8080:8080 --name api demo-api-service
        sleep 5
        curl -X POST http://localhost:8080/api \
          -H "Content-Type: application/json" \
          -d '{"username":"xyz", "password":"xyz"}'

    - name: Clean up container
      run: docker rm -f api

